# Generated by Django 4.0.1 on 2022-09-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='postedBy',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='day',
            name='todoTask',
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoTask', models.CharField(blank=True, max_length=1000, null=True)),
                ('dayID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_id', to='webApp.day')),
            ],
            options={
                'db_table': 'TodoList',
            },
        ),
    ]
