# Generated by Django 4.0.1 on 2022-03-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_day_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='day',
            table='Day',
        ),
    ]
