# Generated by Django 4.0.1 on 2022-09-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_postedby_day_userid_remove_day_todotask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='status',
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
